services:
  frontend:
    build: ./frontend
    container_name: company_frontend
    ports:
      - "5173:5173"
    environment:
      # Browser calls backend directly
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - company_net

  backend:
    build: ./backend
    container_name: company_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=companydb

      # âœ… Email Notifications (use your app password)
      - NOTIFY_EMAIL=virtualwalk3d.shahed@gmail.com
      - NOTIFY_EMAIL_PASSWORD=tpeenhtagwjlovmq

    depends_on:
      db:
        condition: service_healthy   # waits for MySQL
    networks:
      - company_net

  db:
    image: mysql:8.0
    container_name: company_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: companydb
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - company_net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  company_net:
    driver: bridge
